### ISSUE TITLE
CSV Export broken in Development

### ISSUE THREAD

**Issue by vsaw** [opendatacam/opendatacam#360]
Error Message

```
Exporting f65297df-31f4-4375-9504-e6280aeb575b counter history to CSV
(node:69874) UnhandledPromiseRejectionWarning: TypeError: res.csv is not a function
    at /Users/vsaw/Documents/Development/opendatacam/server.js:910:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:69874) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
```

Most likely this was introduced with the eslint fixes.

**Comment by vsaw** [comment]
Fixed in #362.
